export enum ActionType {
  CREATE = 'CREATE',
  DELETE = 'DELETE',
  EDIT = 'EDIT',
  MARK_AS_FAVORITE = 'MARK_AS_FAVORITE',
  SHARE = 'SHARE',
  LEARN = 'LEARN',
  SAVE = 'SAVE',
  PREVIEW = 'PREVIEW',
  STOP_SHARING = 'STOP_SHARING'
}
