export enum SortType {
  NONE = 'NONE',
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
  CREATED_DATE_ASC = 'CREATED_DATE_ASC',
  CREATED_DATE_DESC = 'CREATED_DATE_DESC',
  FRONT_ASC = 'FRONT_ASC',
  FRONT_DESC = 'FRONT_DESC',
  BACK_ASC = 'BACK_ASC',
  BACK_DESC = 'BACK_DESC'
}
